### ISSUE TITLE
Windows 无法执行

### ISSUE THREAD

**Issue by touzi** [chxj1992/hortor_cheater#1]
Windows 通过安装包安装的 mitmprotxy , 然后执行启动 mitmproxy, 在 cmd 执行 python listen.py 执行完成就没有结果了.

**Comment by LCJ-MinYa** [comment]
同楼上.

**Comment by ByteRax** [comment]
+1
通过安装包安装mitmprotxy 

通过pip安装mitmprotxy 

都不行报错信息 can't open file 'mitmproxy': [Errno 2] No such file or directory

**Comment by Sean10** [comment]
@touzi @LCJ-MinYa @tanranran 不是通过python安装的mitmproxy的话，直接使用mitmproxy的指令即可，指令如下

```
mitmproxy -p 8888 -s listen.py
```

**Comment by jomonylw** [comment]
mitmdump -p 8888 -s listen.py

**Comment by touzi** [comment]
终于搞定了
windows 用户请按一下不走操作
1. 去 https://github.com/mitmproxy/mitmproxy/releases 下载 windows-installer 版本然后安装
2. git clone https://github.com/mitmproxy/mitmproxy.git 下载源码
3. cmd 或者 PowerShell 到源码根目录
4. 执行  mitmdump.exe -s .\listen.py
这样就可以运行了

对了还需要修改一下 data = json.loads(content.decode('utf-8')) 改一下这个.

**Comment by chxj1992** [comment]
🎉🎉🎉
