### ISSUE TITLE
小程序显示“似乎断开互联网”

### ISSUE THREAD

**Issue by williamsxu** [chxj1992/hortor_cheater#11]
现象：mac安装好mitmproxy，并且iOS设备安装好证书，但是一进入小程序就登录不上并显示“似乎断开互联网”。
问题：是否因为代理的原因无法通过SSL验证导致的？

**Comment by chxj1992** [comment]
IOS 需要在系统把证书设置为可信任.  “设置”>“通用”>“关于本机”>“证书信任设置”
