### ISSUE TITLE
提示证书无效

### ISSUE THREAD

**Issue by BeyoundCong** [chxj1992/hortor_cheater#4]
安装了之后    打开头脑王者的时候， 提示request:fail 此服务器的证书无效， 估计是小程序  验证服务器地址了，  作者现在还能成功么？  我是用的 iOS 11 版本。

**Comment by chxj1992** [comment]
Iphone要在 "设置" -> "关于手机" 里设置信任证书

**Comment by BeyoundCong** [comment]
@chxj1992  谢谢， 我知道了 确实是没有点击信任的。   现在小程序把我给禁止点击了， 我现在要试试  飞行模式下  多等一会   看能不能给解封。

**Comment by chxj1992** [comment]
哈哈哈
