### ISSUE TITLE
运行命令报错

### ISSUE THREAD

**Issue by wonderffee** [chxj1992/hortor_cheater#5]
python mitmproxy -p 8129  -s listen.py
python: can't open file 'mitmproxy': [Errno 2] No such file or directory
是mitmproxy 要放在当前文件夹下吗？感觉不像啊

**Comment by chxj1992** [comment]
抱歉, readme写错了, 没有前面那个python,  应该执行 `mitmproxy -p 8129  -s listen.py`,  已订正
