### ISSUE TITLE
request:failed

### ISSUE THREAD

**Issue by openfe-openfe** [chxj1992/hortor_cheater#7]
问题：打开头脑王者就会出现request:failed 此服务器的证书无效。您可能正在连接到一个伪装成"question.hortor.net"的服务器，这会威胁到您的机密信息的安全

只有关掉http代理才可以打开头脑王者小程序

**Comment by openfe-openfe** [comment]
证书下载 且信任了  ios11

**Comment by sjxt** [comment]
+1
